### ISSUE TITLE
Show game setup data before first jam

### ISSUE THREAD

**Issue by dhmay** [dhmay/jamstats#118]
Right now, when connecting to a scoreboard for a game that hasn't started yet, the DerbyGame object fails to build, and the user gets a "can't connect" error. 

Instead, I'd like to make available:
* full rosters
* indications on all the other pages that you're successfully connected to the scoreboard and there will be data there when the game starts
* countdown to derby, if I can grab that

**Comment by bullseye555** [comment]
YESS!! <3

**Comment by dhmay** [comment]
@bullseye555 I've started on this. [This build artifact](https://github.com/dhmay/jamstats/actions/runs/4422254634) will tell you the game hasn't started if you try to show any plot except the rosters. And it displays the game status across the top of the screen at all times.

I'd still like to let the user see the lineup before the first jam. Right now, no data displays until the first jam starts. How important do you think that feature would be?

**Comment by bullseye555** [comment]
I think it would depend on in-game behaviour

Lets say Jam 5 has just finished, and the lineup for Jam 6 has been input - will the lineup for Jam 6 show up straight away, or only once Jam 6 has started? 
If it's only ever going to show the lineup once the jam has started, then I think that not having the lineup prior to the start of the period (so Jam 1 for P1 and P2) isn't a deal breaker. 

On the flip side, I would be hesitant to have it change over as soon as the LT's begin inputting the data, as this will change what's displayed to the Commentators and they may be talking about what's happened and using the lineup information

Thinking "out loud", how hard would it be to have two tables (I'm 100% sure on data presentation in the JSON if this would be possible, but it'd solve a conundrum of "What Lineup Data do we show?!" ?
Table 1 Title: (context dependent) "Upcoming Jam" or "In Progress Jam"
Table 1 Contents: Lineup data for the Jam that is about to happen (as the LT's are inputting it during lineup). Once the Jam starts, this becomes "In Progress Jam"

Table 2 Title: Previous Jam
Table 2 contents: Lineup data for the jam that has just occurred. EG: If it's currently the lineup between Jams 5&6, then this will show Jam 5 data (with Jam 6 in Table 1). 

As soon as the Jam finishes, data from Table 1 moves into Table 2, and Table 1 is blank until the LT's start inputting who is on track

The Two Table idea could also be an _Alternating_ pair. Table 1 is _Jam -1_, and Table 2 is _Current/Upcoming Jam_. Then once Current Jam finishes, that data _stays_ in Table 2 (Now _Jam -1_) and Table 1 becomes _Current/Upcoming Jam_
Or Table 1 is _Upcoming Jam_ only (so only shows data during Lineup) and Table 2 is Static (Showing previous Jam during Lineup, or Current Jam with the Jam Clock is running)


Sorry - a lot of word vomit there.... 

I'll have a look at the artifact later today

**Comment by dhmay** [comment]
> I would be hesitant to have it change over as soon as the LT's begin inputting the data, as this will change what's displayed to the Commentators and they may be talking about what's happened and using the lineup information

That's a *really* good point. I had been thinking that a commentator would like to get in mind ahead of time who's going to be the jammer, but it would not be great if they named the jammer over the mic. 

I was thinking about a two-table situation, too... maximally, I could show *every* jam, but I can't imagine anyone would want to look back over the whole period. But just one previous jam could be occasionally useful.

FYI, the *latest* build artifact also improves the auto-refresh function. If there's new game data, and it's been >2 seconds since the last refresh, UI will refresh immediately rather than waiting 2 seconds.

**Comment by bullseye555** [comment]
>but it would not be great if they named the jammer over the mic.

As long as they're not talking tactics and only talking about what's happening that everyone can see, it doesn't really matter.

Before the Jam Start:
"crAbby has lined up on the jammer line for Pivot City" - factual, no issues
"crAbby has lined up on the jammer line for Pivot City, and is looking to exploit the hole on the outside line left BlockerTown" - Tactical, shouldn't happen

Commentators **should** only be talking about what IS or DID happen, not what SHOULD/COULD happen, but there's no rule against it... so... ¯\_(ツ)_/¯ 


And yeah - having every jam would be overkill for what they're going to use it for. 
"This Jam" and "Last Jam" should be more than enough

**Comment by dhmay** [comment]
OK, @bullseye555 , I gave "Current Jam" and "Previous Jam" a try (latest build). Please give it a spin!

**Comment by bullseye555** [comment]
Ok - Feedback based on push 354

_Current Skaters_ looks great with the _Current_ and _Previous_ jam tables
The _Current Skaters_ only updates once the Jam is live (not sure if you wanted it to update between jams - but I suspect this is expected behaviour)
The one issue I found was that a skater penalised in the previous Jam had all the updates in the _Previous Jam_ (so in the screenshots here, the penalty was issued in P2J1, and they didn't sit/serve until P2J2
![image](https://user-images.githubusercontent.com/28804763/225242617-08b17af3-885b-4a5b-b593-dc1e960d311f.png)
![image](https://user-images.githubusercontent.com/28804763/225242640-f7a36d17-4c65-44be-81eb-4e2c5e5ce64e.png)
![image](https://user-images.githubusercontent.com/28804763/225242647-7872cdc8-c203-4729-8a80-3fe5f10366fb.png)

I then _Finished_ the DCRD/NERD v TVC game and started a new one (KCR v WSRD) and the _Finished_ game remained on screen and never refreshed. 
When I tried to change a page, all I got was a "Waiting for ..." message from my browser
![image](https://user-images.githubusercontent.com/28804763/225244162-c761473f-7bb2-4cdf-a8ec-3add99e6fd2a.png)
It looks like JS picked it up (the underlined is the new game ID)
![image](https://user-images.githubusercontent.com/28804763/225244379-a0f275b2-3d6c-4348-bd8f-71a3d69e6161.png)

If I Stop & Restart JS, it picks it up no issue
![image](https://user-images.githubusercontent.com/28804763/225244679-81414aaa-9a9d-474f-9ce4-845ed7bb27af.png)

And the _Roster_ is available, with all other pages showing "Not yet started"
![image](https://user-images.githubusercontent.com/28804763/225244814-e75bc986-0523-4dc6-be39-e8263bab4c4f.png)
(had an Idea while on this page - will drop an FR for it shortly!)

**Comment by dhmay** [comment]
I opened #123  for the "start a new game after game finishes" issue.

**Comment by bullseye555** [comment]
>I look for any "serving" or "not yet" penalties (should just be "serving") from the previous jam. If there are any:
>CHANGE the status in the last jam to "Next Jam"
>REPEAT the penalty in the current jam, with the appropriate status

I'm not sure this will cover all scenarios... What happens if a penalty (or multiple, so sitting for 1 min or more) isn't _Served_ in the following Jam. EG:
- Skater issued Penalty + Insub [which reminds me... I didn't look to see how it handled multiple penalties... I'll do that at some point today] and Jam ends before they've sat in the box
- In Jam +1 it only goes for 20 seconds, so they haven't even finished their first penalty yet
- In Jam +2 it only goes for 35 seconds, so they _still_ have 5 seconds left to serve before being released in Jam +3
(This is a real scenario, that happened in a game I was at on the weekend - even if they'd only gotten a single penalty, they'd have been in the box for more than 1 Jam)
If you're just looking at the previous Jam's data the penalty will drop off in Jam +2 and they'll _see_ a skater in the box, but not _why_

>One sticking point: what happens when the penalty is served? If I do nothing, it will disappear from the current jam, and show as "served" in the previous jam. That's technically correct (penalty was from the previous jam), but is it too confusing?

IMO, at minimum the status should be reflected in the relevant Jams (EG: If the penalty is served in the Jam following, then the status is updated in both the Penalty Issue Jam and Jam +1)
If we _really_ want to run down the rabbit hole, using the above scenario the ideal situation would be that the Status in the Jam reflects what happened in **that** Jam. EG, after the penalty has finally been served
- Penalty Jam, the status would be _Net Yet_ [and because we're only showing Current Jam -1, this wouldn't be shown at all once Jam +2 starts]
- Jam +1, the status would be _Serving_
- Jam +2, the status would be _Served_ [once they've left the box]

**Comment by dhmay** [comment]
Good point about the possibility of serving a penalty two jams later... that's easy to address, at least mostly: I can just look back over the last say 50 penalties and pick out any that are still being served and repeat them in the current jam. The penalty from 2 jams ago would get dropped out of "previous jam", but at least the current jam would be correct.

The other stuff is harder. The effect of new data from the scoreboard is *supposed* to be to cancel out old data of the same type. I.e., an update on a penalty should null out the old row and replace it. That's what I'm doing now, which is why I'm limited to "most recent data" about each penalty. I could change the way I'm approaching that, but it might be a can of worms.

**Comment by bullseye555** [comment]
I think we can live with the current jam having the active status in it.
That'll account for all Penalties, and not having it in the Previous Jam
isn't going to have that great an impact

If I get time, I'll have a look at how the LT paperwork is generated on the
Scoreboard, as that will always have the Start and Ending Jam of a penalty.
There might be something in the JSON we haven't picked up on that shows
it...

**Comment by bullseye555** [comment]
Ok - Looks like it doesn't handle multiple con-current penalties.
Ideal handling would be to list all penalties (eg: **Back Block** and **Misconduct** for this one), but if that's not possible then having **Multiple Penalties (2)** would be the next best thing (where the number inside the brackets is the count of penalties)

![image](https://user-images.githubusercontent.com/28804763/225461674-2798b020-fcfa-48f7-a18a-032c631b79c7.png)
![image](https://user-images.githubusercontent.com/28804763/225461708-9fe332a8-0757-4af5-85a9-02f495df04a9.png)

**Comment by dhmay** [comment]
@bullseye555 , the latest build artifact should handle pulling "Serving" and "Not Yet" penalties from earlier jams into the current jam. 

It doesn't handle multiple penalties (that's a trickier fix, so separating into the other issue). If there are multiple penalties, it'll show the most recent penalty they're currently Serving.

**Comment by bullseye555** [comment]
>the latest build artifact should handle pulling "Serving" and "Not Yet" penalties from earlier jams into the current jam.

Looks good, but it does look like it's updating the _Previous Jam_ when the skater has a penalty in the previous jam _and_ the current jam. If this is tough to fix, it not a big issue
![image](https://user-images.githubusercontent.com/28804763/226162752-8594897d-8924-4773-9870-3afae0ab84a3.png)

**Comment by dhmay** [comment]
Thanks for catching that, @bullseye555 ! Latest build artifact should fix it.

**Comment by bullseye555** [comment]
[96a8c12](https://github.com/dhmay/jamstats/commit/96a8c12f483d2cc251e461f9b3717c2dbbb85437) is the latest one showing for me - is that right? 
![image](https://user-images.githubusercontent.com/28804763/226210225-035dce0d-4298-4925-ac2e-50af7fc703bd.png)

**Comment by dhmay** [comment]
Yeah. But I took a look, and I must've screwed something up, because it was missing several recent changes. The newest artifact, d967a5b, is up to date.

**Comment by bullseye555** [comment]
Lol - looks good now
