### ISSUE TITLE
Invalid async_mode specified

### ISSUE THREAD

**Issue by someweisguy** [dhmay/jamstats#159]
Hello - thank you for this awesome application! I'm really looking forward to using it soon. However, I am unable to get the app running. Upon startup, when I load my configuration I get the following error:

```
Starting SocketIO Flask app...
[15572] Failed to execute script 'jamstats' due to unhandled exception!
Traceback (most recent call last):
  File "jamstats", line 251, in <module>
  File "jamstats", line 217, in __main__
  File "jamstats\web\statserver.py", line 193, in start
  File "flask_socketio\__init__.py", line 187, in __init__
  File "flask_socketio\__init__.py", line 243, in init_app
  File "socketio\server.py", line 134, in __init__
  File "engineio\server.py", line 151, in __init__
ValueError: Invalid async_mode specified
```

I am running jamstats v1.4.0 (the log says I'm running v1.3.0, but I downloaded the latest release), with CRG v2023.4 on a Windows 10 computer. I came across this bug by running CRG and jamstats on one machine, loading up jamstats, pointing jamstasts to `localhost:8000`, and clicking start.

Relevant line seems to be [here](https://github.com/dhmay/jamstats/blob/main/src/jamstats/web/statserver.py#L193) and Flask-SocketIO [documentation](https://flask-socketio.readthedocs.io/en/latest/api.html#flask_socketio.SocketIO) does not seem to indicate this error should happen, naturally. :)

I did find [this stackoverflow post](https://stackoverflow.com/questions/54150895/valueerror-invalid-async-mode-specified-when-bundling-a-flask-app-using-cx-fr) which may be helpful!

I'm happy to help do some troubleshooting! I only have a teensy bit of experience with Flask, but I am happy to read documentation as well.

**Comment by someweisguy** [comment]
Of course, as soon as I hit submit, I see that you [may already be aware of this issue](https://github.com/dhmay/jamstats/blob/main/src/jamstats/web/statserver.py#L50-L52)!

**Comment by dhmay** [comment]
Yes, indeed, I ran into the same issue on Windows a while back, and I tried to fix it with those lines I commented out. I left them in the code, commented out, because I wasn't 100% confident in the workaround I eventually found (which was specifying the version of gevent and gevent-websocket in requirements.txt and setup.py).

And it looks like I had reason not to be. The "good" news is I can reproduce the problem -- I have a Windows box that's kind of a pain for me to use, so I put out the last release without verifying it on Windows. Bad me! I'll get it figured out, close out this bug and put out a new release.

Also, thanks for the headsup about the log saying 1.3.1 instead of 1.4.0! I obviously missed that, will fix it in the release where I fix this bug.

In the meantime, it looks to me like version 1.2.1 runs without this problem. So, you can try that for now, but that version of JamStats might have trouble with the v2023 version of CRG.

So, I'll try to fix this ASAP!

**Comment by dhmay** [comment]
Oh! @someweisguy , actually I can't reproduce this bug on JamStats v1.3.0, either. That's really odd, since nothing I changed since then should have anything to do with it. But the good news there is that v1.3.0 should work fine with CRG v2023!

**Comment by dhmay** [comment]
(note to me: I think the reason this started failing between 1.3.0 and 1.3.1 is that it was re-broken by a new version of a dependency package, likely python-engineio, gevent or gevent-websocket. Next to try: pin those dependency versions to known working versions)

**Comment by dhmay** [comment]
(reinstating the monkeypatch line didn't work, either. My new guess is that between 1.3.0 and 1.3.1 I moved some code around and changed the order in which packages were imported before app.start() gets called)

**Comment by dhmay** [comment]
So far, I've gone down the following alleys:

* [This stackoverflow thread](https://stackoverflow.com/questions/54150895/valueerror-invalid-async-mode-specified-when-bundling-a-flask-app-using-cx-fr). It lists some packages that need to be explicitly loaded because they won't be automatically loaded by cx_Freeze. I've added all of those *except eventlet*, which gave me problems, and still gotten the issue.
* [This stackoverflow thread about eventlet](https://stackoverflow.com/questions/75137717/eventlet-dns-python-attribute-error-module-dns-rdtypes-has-no-attribute-any). I thought I'd found a solution to the problem of loading eventlet, which was to lock down the version at 2.2.1 (a version that should have the ANY attribute it's complaining about). That didn't work -- even when locking eventlet at 2.2.1 it complained about the ANY attribute.

**Comment by dhmay** [comment]
Well, that was an adventure. I believe I've fixed the bug, @someweisguy , but the fix is a bit of a house of cards. As you noticed, I'm using Flask. As you noticed, there's quite a lot of brittleness under Flask, particularly when packaged with PyInstaller. The fix I believe I have working involved:

* declaring a bunch of hidden dependencies that otherwise weren't getting loaded
* switching from eventlet to gevent (I'm not sure if that's necessary)

I've pulled the fix into the main branch. So, if you're comfortable running from source, you should be able to run that way; that would probably the easiest for troubleshooting if you run into trouble. 

Otherwise, do you have access to the jamstats-Windows.zip artifact [here](https://github.com/dhmay/jamstats/actions/runs/6636173078)? I think you should, as long as you're logged into GitHub. You should be able to download that, unzip it, and run it.

Please let me know if this works! Like I said, my Windows box access isn't great, so I have trouble thoroughly vetting changes on Windows. If this basically seems to be working (I'm particularly interested in whether it's properly automatically updating with new data from the scoreboard), I'll put out a new version of JamStats with the fix ASAP.

**Comment by dhmay** [comment]
Incorporated this fix into v1.4.1.

**Comment by someweisguy** [comment]
Wow - you are a magician. Thank you again for the excellent work!

**Comment by dhmay** [comment]
Let me know how it goes! I appreciate any feedback, positive or negative.
