### ISSUE TITLE
[BUG REPORTS] Visualisation of the Stats

### ISSUE THREAD

**Issue by bullseye555** [dhmay/jamstats#16]
Had a chance to have a play with it tonight - UAT is part of my role at work, so apologies if this seems like I'm nit-picking - I'm just picking up things I see; I know this is 95% there, just hoping this helps get you the last 5%! 

[game_plots.pdf](https://github.com/dhmay/jamstats/files/10193262/game_plots.pdf)
[STATS.json.txt](https://github.com/dhmay/jamstats/files/10193327/STATS.json.txt)

Printing a gameplot, the first page seems a bit out out of kilter
![image](https://user-images.githubusercontent.com/28804763/206663361-e65d9449-0a62-4c96-89de-adda3bda0e1d.png)

Second page table has **n_scoring_trips** as the final column name [suggest changing the name of the column] - based on the game data [above], there should only be ~50 trips for _Team 1_ [Suggest also changing this to the team _name_] (on the assumption that this column is counting the number of trips that were scored on only, or ~70 if including trips where the score was 0)
![image](https://user-images.githubusercontent.com/28804763/206669359-f617cce4-5bc1-4360-bd1e-549ce3b4663b.png)

Points per Jam **O** and **X** seems to overlap the Jam Number
![image](https://user-images.githubusercontent.com/28804763/206664758-4e0a4dae-8965-4665-a868-4d2b9e9ca288.png)

**Comment by dhmay** [comment]
Thanks for the bug reports, bullseye555! I think the last one is something I didn't notice because it's dependent on the score of the highest-scoring jam. I should be able to deal with these... I'll probably make several changes to that plot, because I'd also like to capture whether the jam was called off or there was a star pass.

**Comment by dhmay** [comment]
I revamped the main jam score plot. Let me know what you think of this, @bullseye555.

I'm finding it difficult to visually connect all these different elements per jam. There's an enormous amount of information represented here... can you think of any better way to help people get their brains around it? I could remove some stuff, like star pass and no-initial, just to make things simpler.

![image](https://user-images.githubusercontent.com/714077/206837898-77579cc8-16f8-44f2-ab52-27fc5793814a.png)

**Comment by dhmay** [comment]
Also, I fixed the two tables. 
![image](https://user-images.githubusercontent.com/714077/206838049-ce0303a8-8966-4b2b-bddc-1b645f88cf31.png)

![image](https://user-images.githubusercontent.com/714077/206838041-ae26c4de-e0fb-4d47-807f-b6613141eccb.png)

I simply removed n_scoring_trips from the game summary table, because I don't know why it wasn't adding up!

**Comment by dhmay** [comment]
Fixed in version 0.1.2, but I'm happy to keep iterating on that plot.

**Comment by bullseye555** [comment]
@dhmay - I think it's a good representation of what's happened. Leave it as-is for now, and see what the rest of the users come back with feedback on :)

**Comment by dhmay** [comment]
@bullseye555 - Slight improvement: I'm breaking up by period, now, so there's just less data; and I added lines to indicate jam.
![image](https://user-images.githubusercontent.com/714077/206864053-2e4af741-dd32-4373-91da-5d215f2b3983.png)

**Comment by dhmay** [comment]
Improved more.
![image](https://user-images.githubusercontent.com/714077/206871641-7fc064f0-4b57-490a-96b6-f6de5edfc5d2.png)
