### ISSUE TITLE
Penalties being misinterpreted

### ISSUE THREAD

**Issue by uujfwmnp** [dhmay/jamstats#177]
**Describe the bug**
Some players have the wrong penalty listed in the output of Jamstats

**To Reproduce**
Add a number of players with various single game penalties in CRG, run the CRG JSON stats through Jamstats (web or PDF)

**Expected behavior**
Correct player penalties shown

**Screenshots**
![image](https://github.com/dhmay/jamstats/assets/3219994/a0db9aba-76c3-4687-ac19-f2d679b02303)
![image](https://github.com/dhmay/jamstats/assets/3219994/2c954048-4790-462c-8bf7-00e3583ea400)

**Additional context**
I was back-filling penalties into a completed game, the data was not being entered into a live match.

**Comment by dhmay** [comment]
Thank you for pointing this out! So, it looks like the correct penalties are getting captured, but they're getting associated with the wrong skaters on the right team? That's what I'm inferring from your second image.

**Comment by uujfwmnp** [comment]
Yep! The mixup only happened with skaters that had a single penalty, but it
did not affect all of them.Message ID: <dhmay/jamstats/issues/177/2105941603
@github.com>

>

**Comment by dhmay** [comment]
I think I fixed it. The problem was that I was literally just sorting the skater data (name, jams... everything but penalties) by how many penalties they had. No surprise that caused this bug!

I _believe_ I've fixed the problem. Are you on Windows, @uujfwmnp ? If so, could you please try downloading [this zipped .exe file](https://github.com/dhmay/jamstats/actions/runs/9047145177/artifacts/1494089898), running JamStats from that, and see if it looks fixed to you?

**Comment by uujfwmnp** [comment]
That did the trick, thank you! The skater data sorting actually did affect more skaters than I realized once I did side-by-side comparisons. I think we can close this ticket. :)

**Comment by dhmay** [comment]
Great! Fixing in 1.4.12.
