### ISSUE TITLE
JamStats for iPad?

### ISSUE THREAD

**Issue by heliogoodbye** [dhmay/jamstats#180]
**What version of the tools are you running, and how?**
Currently using JamStats for Mac, v1.4.12

**Is your feature request related to a problem? Please describe.**
No problem, just an app request.

**Describe the solution you'd like**
I'd love to see a version of JamStats for the iPad.

**Additional context**
I'm an announcer who self-produces and currently use both an iPad for live CRG scoreboard/penalty tracker feed and a MacBook Pro for JamStats. JamStats is such a vital tool for my needs, and I'd love to be able to walk around with just the iPad instead of having to use two devices. The online version is nice, but it requires a json file to upload, which I don't always have on the ready. I like how the Mac app can plug into the IP address of the CRG scoreboard directly, and that's the kind of functionality I'd like to see on the iPad.

**Comment by dhmay** [comment]
I've looked into ways I could build JamStats for the iPad, and I really don't think I can, without someone to do a lot of work to help me port it.

However! I do have a solution for your specific problem: just run Jamstats on your laptop, and connect to your laptop from your iPad. 

When you run Jamstats on your laptop, it starts a webserver, and you can access it in your browser at `localhost://<port number>`, where <port number> is probably 8080 unless you specify otherwise. If your iPad is on the same server as the laptop, you can just point your browser to the IP address of your laptop and hit that port, e.g., `192.168.1.5:8080`.

Let me know if that works for you!
