### ISSUE TITLE
colorizing schemes for players on Jammer Stats pages should be aligned

### ISSUE THREAD

**Issue by erevrav** [dhmay/jamstats#50]
**What version of the tools are you running, and how?**
v0.2.0-alpha

**Is your feature request related to a problem? Please describe.**
The colorizing schemes for players on the two Jammer Stats pages are really different.
- the first page colorizes each skater with a smooth progression of hues from peach, to green, to blue, to pink. (somewhat like the progressions Brewer uses in https://colorbrewer2.org/#type=diverging&scheme=RdYlGn&n=10)
- the second page colorizes each skater with very different colors from one skater to the next (like one of Brewer's qualitative sets
https://colorbrewer2.org/#type=qualitative&scheme=Set3&n=10)
![image](https://user-images.githubusercontent.com/26390183/209280152-00263500-e838-479e-a51e-b2b8a5d07f83.png)

**Describe the solution you'd like**
I'd like the two pages to have the same visual language. The progression is pretty, but not actually relevant (you're not intending to one skater the next (or at least they're not sorted to suggest that you are). The qual scheme may make more sense from that perspective, but it's not as pretty.
Pick only one of those colorizing schemes or something else, but not both.

**Comment by dhmay** [comment]
What's happening here is that team 1 has more jammers than team 2. So, Seaborn (the plotting engine) uses most-easily-differentiable colors for team 2, but throws up its hands for team 1 and shifts to rainbow.

My thought: Determine whether Seaborn is going to throw up its hands for either team. If neither, they both get high-contrast. If both or if just for one, then they _both_ get rainbows, rather than the current  disparity.

Sound good?

**Comment by erevrav** [comment]
nice: reliably differentiable when it can be, and reliable pretty when it can't.

**Comment by dhmay** [comment]
Fixed. Rainbow palette with a number of colors that's the maximum of the two teams' jammer counts.
