### ISSUE TITLE
put version number for executable in file properties

### ISSUE THREAD

**Issue by erevrav** [dhmay/jamstats#64]
**What version of the tools are you running, and how?**
v0.3.3-alpha

**Is your feature request related to a problem? Please describe.**
I'd like to know what version of jamstats I'm running. date-of-download isn't very authoritative. 

**Describe the solution you'd like**
I'd like the file properties in windows to show the version number. (in this place on Windows, and the analogous places on Mac & Linux if you end up building executables for those.)
![image](https://user-images.githubusercontent.com/26390183/209723926-3749f793-b20a-4b4c-9ce0-090455fc83fe.png)

**Describe alternatives you've considered**
manually renaming the file to jamstats-033.exe after I download it

**Comment by dhmay** [comment]
Oh, interesting. I don't know how to do that, but I can give it a go.

I *had* implemented adding the jamstats version in a message on the commandline and also wrote it on all the plots. However, the way I did that broke the Windows executable, so I had to undo it.

So, let's use this enhancement to track all that stuff.

Another thing I could do is start having the releases contain, e.g., `jamstats-v0.3.3.exe` rather than `jamstats.exe`. I go back and forth on that. What do you think, @erevrav ?

**Comment by dhmay** [comment]
Wait... if you're running v0.3.3-alpha, how's come you're still seeing that awful red logo? Didn't it turn blue/green for you somewhere around v0.3.1-alpha?

**Comment by erevrav** [comment]
I don't love changing the name with each version, because Ive got a Windows shortcut file that passes the anonymize flag at to the command line. But it wouldn't kill me if you have to go that route. 

(I'm running an errand but will check on the logo assets when I get home.)

**Comment by dhmay** [comment]
I went that route for now, in v0.3.4 (which contains a Mac executable!). We can revisit the strategy.

0.3.4 also fixes the icon. Turns out I just hadn't updated it.
