### ISSUE TITLE
FR - Running EXE asks for options

### ISSUE THREAD

**Issue by bullseye555** [dhmay/jamstats#68]
**What version of the tools are you running, and how?**
Windows EXE v0.3.4

**Is your feature request related to a problem? Please describe.**
When running the EXE file, it would be useful for a pop-up prompt for the options available instead of having to use command prompt - while this isn't an issue for me, some less technically minded people would not be able to use JamStats at the moment

**Describe the solution you'd like**
Run the JamStats EXE file and have a prompt that asks for:
- JSON file to be uploaded; OR
- CRG IP and Port to connect to
With additional options to:
- Select Theme
- Set Team Colours
- Set Output Location/Type (eg: File path or WebServer Port)
- Anonymise options

**Describe alternatives you've considered**
nil

**Additional context**
Sample of screen for an Electronic Jam Timer as a sample

![image](https://user-images.githubusercontent.com/28804763/210977679-0730acd1-8e1d-4176-9a04-1298c65748ca.png)

**Comment by dhmay** [comment]
I'll try to do this the "easy" way with [Gooey](https://github.com/chriskiehl/Gooey), though that'll add more library dependencies to the project (and make the .EXE bigger and maybe slower). If Gooey doesn't do it for me I'll build something with tkinter.

First attempt will be bare-bones. If people start using it and are clamoring for more (e.g., color dropdowns for the teams) those can be separate FRs.

**Comment by dhmay** [comment]
Oh, one question, @bullseye555 : for this to be useful to people, do you think the GUI needs to be the default behavior if the  .EXE is double-clicked? Or would it still be useful if they had to go to the commandline and type "jamstats.EXE --gui"?

I ask because making it the default behavior will break the usual Unix/Mac commandline expected behavior of "run it with no arguments to get the usage docstring".

**Comment by dhmay** [comment]
This stackoverflow solution should be helpful:
https://stackoverflow.com/questions/56580102/clever-ways-of-switching-between-gui-and-cli-modes-with-gooey

**Comment by dhmay** [comment]
OK, I added the GUI for argument capture. You get it if you run the thing with no arguments (or, presumably, if you just double-click the EXE in Windows). It looks like this:
<img width="620" alt="image" src="https://user-images.githubusercontent.com/714077/211129633-152aaf74-3e4e-4bfa-9b3f-689b42838a43.png">

Upside: I think it looks fantastic (YMMV, and I'm open to suggestions for tweaks, mostly on the help language)

Downside: it depends on the "gooey" package, which depends on wxpython, which took *forever* to install in my Python installation. So, I'm worried it'll bulk up the executable and make it slow. @bullseye555 , please test it out and let me know how it goes. You can download the executable with the gui (zipped) [here](https://github.com/dhmay/jamstats/suites/10232889350/artifacts/501644275).

**Comment by dhmay** [comment]
I realize that *typing* or *cut-pasting* in the input filename is difficult, maybe nearly as difficult as running the tool from the commandline. The reason I did it that way is that I wanted to preserve the drag-and-drop interface. For that to work, jamstats has to be able to accept a single argument that is (or can be) a file. That's why I overloaded the single argument to be either a file or a port number.

I can't think of a good way around that -- that is, to make the input file argument be of a "file" type, so that the gui would give you a file chooser. I could make multiple executables... that's more work and more for people to manage. I could have a "--webserver" argument that would switch the behavior... but then you'd still need to input a filename as the first argument, which wouldn't make any sense.

Do you think having to supply that file argument through the text box will be a deal-breaker for people who would want to use this GUI?

**Comment by dhmay** [comment]
The other option is to give up the drag-and-drop interface.  Then I could let the user use a file chooser if reading a json file or specify a server and port if connecting to a webserver.

How important do you think the drag-and-drop is?

**Comment by bullseye555** [comment]
In answer to your questions: (I'm about to download the file you linked and have a play with it, so this is before I've used it)

>  for this to be useful to people, do you think the GUI needs to be the default behavior if the .EXE is double-clicked? Or would it still be useful if they had to go to the commandline and type "jamstats.EXE --gui"?
I think having it has default behaviour when double clicking the EXE would be the expected behaviour [In the same way that just double clicking the CRG _Scoreboard.exe_ file just runs CRG, but you can still run via CMD with parameters

> Do you think having to supply that file argument through the text box will be a deal-breaker for people who would want to use this GUI?
I think it's more user friendly, and is definitely going to be adopted quicker if the GUI interface in more intuitive - having said that

> The other option is to give up the drag-and-drop interface. Then I could let the user use a file chooser if reading a json file or specify a server and port if connecting to a webserver.
> How important do you think the drag-and-drop is?
I think having the file chooser over drag-and-drop would be more user friendly - especially if the drag-and-drop means having to manually enter the file location

**Comment by bullseye555** [comment]
@dhmay - Error running the EXE
![image](https://user-images.githubusercontent.com/28804763/211131497-c66fc285-491c-49a9-a5df-120c0060e1fa.png)

**Comment by dhmay** [comment]
Shoot! Sorry, I'll debug over the weekend.

**Comment by bullseye555** [comment]
All good

Confirming same error after installing wxpython and gooey

![image](https://user-images.githubusercontent.com/28804763/211131611-ec958800-b851-48db-be35-d7cf29ff7d19.png)

**Comment by dhmay** [comment]
Hm, I *might* have fixed it here:
https://github.com/dhmay/jamstats/suites/10233483509/artifacts/501729428

But I need to verify on a windows box.

**Comment by bullseye555** [comment]
It starts, yay!
![image](https://user-images.githubusercontent.com/28804763/211132473-423d620d-5664-49cf-9ff2-2f61dbf1c979.png)

But it fails to run :( 
![image](https://user-images.githubusercontent.com/28804763/211132431-2cc4299b-e00c-44a5-8d26-64aea1db6384.png)

**Comment by bullseye555** [comment]
It does work via CMD though 
![image](https://user-images.githubusercontent.com/28804763/211132560-5ae9babb-6fa2-4e14-a2b5-283598df2fb0.png)

**Comment by dhmay** [comment]
OK, this time I think I got it. I changed the usage as you suggested -- there are now two options for the input argument and two for the output argument, and that allows you to use file choosers if the input or output is a file. Since there's no longer a single argument for input, drag-and-drop will no longer work.

https://github.com/dhmay/jamstats/suites/10233856743/artifacts/501757390

I'm getting some weird behavior with the input file chooser, with it warning me that it was going to save over the file (even though it was opening it read-only). I'll dig into that. That was on a mac, though, and I'm curious whether you get the same on Windows.

**Comment by dhmay** [comment]
(if you do get that scary overwrite warning you can just click through it to open the file properly)

**Comment by bullseye555** [comment]
Confirming GUI opens and runs (see #76 for WebServer plotting bugs)

Also confirming that I do get the _Confirm Save As_ dialogue box after selecting the file
![image](https://user-images.githubusercontent.com/28804763/211147293-c981c02e-2100-4c03-834a-04d030ba5a4f.png)

It looks like the _Browse_ window is opening a **Save / Save As** dialogue instead of an **Open File** dialogue, which is why it's throwing the prompt - the OS recognises the file exists, see's that it's a **Save** dialogue so throws the _This file already exists_ warning
![image](https://user-images.githubusercontent.com/28804763/211147324-e1766310-8b12-44a8-8225-38e6c452e72d.png)

**Comment by dhmay** [comment]
Fixed!

**Comment by bullseye555** [comment]
Confirmed working on a Windows box, too
