### ISSUE TITLE
FR - When connected to Scoreboard, Auto-Refresh data every 60 seconds

### ISSUE THREAD

**Issue by bullseye555** [dhmay/jamstats#89]
**What version of the tools are you running, and how?**
v0.3.4 with patches, via Windows EXE 

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Instead of having to manually refresh a page during the game, have the JS WebServer auto-refresh every 60 seconds

**Describe alternatives you've considered**
A browser extension would be useable to force the refresh, but this would rely on a 3rd party piece of software

**Additional context**
The refresh could be every 30 seconds - or configurable (but no less than 30 seconds to avoid un-needed load on the server

**Comment by dhmay** [comment]
Totally a good idea. I had this on my mental to-do list but not, like, on an actual to-do list. :)

It should be pretty easy to implement. I think I can do it in the next week or so.

**Comment by dhmay** [comment]
Done! I went with every 30 seconds. You can try it in this build:
https://github.com/dhmay/jamstats/actions/runs/3909041747

Note that, even if you hit the refresh button, jamstats will refuse to bug the scoreboard any more often than every 30 seconds. You should be able to see that in the timestamp in the left sidebar: if you keep reloading the page, that timestamp won't change until 30 seconds have gone by since the time shown.

**Comment by dhmay** [comment]
(I'd like to make the refresh interval configurable, and enable turning off auto-refresh, but that will need to wait for more free time)

**Comment by bullseye555** [comment]
Looks great, and works perfectly! 

There's one more FR I've identified and have a comment on one of the other changes - will add them shortly
