### ISSUE TITLE
Don't repeatedly pull full JSON from CRG

### ISSUE THREAD

**Issue by frank-weinberg** [dhmay/jamstats#96]
The \<crg\>:/SaveJson/ interface is not intended for repeated queries, especially mid-game, as it creates notable load on CRG. When multiple people are running Jamstats to get stats from the same CRG instance running on a weaker computer, it might affect the game in progress.

Clients that want to update data during a game should use the WS interface and register for the subset of data they need. (Here that would probably be "ScoreBoard.CurrentGame" or "ScoreBoard.Game(\<id\>)".) This will also mean data is pushed instead of pulled, allowing for a better user experience, as updates can happen as soon as new data is available instead of having to wait for the next pull.

**Comment by dhmay** [comment]
I hope jamstats hasn't been slowing anyone's scoreboards down!

To be clear, what I'm doing is hitting: `http://{server}:{port}/SaveJSON/scoreboard-0-secs-ago.json`. I had been assuming that the scoreboard was caching those json files, since there's one for 10-secs-ago and 30-secs-ago (or something like that). If the URL I'm hitting causes the whole json to be regenerated, would one of those other two instead grab a cached file? I wouldn't at all mind being 30 seconds behind.

If I grab the data from the WS interface and specifically get "ScoreBoard.CurrentGame", will that give me the full game data each time, or will each call get me incremental data? I don't want to have to rely on jamstats being connected since the start of the game... if that gives me incremental data I could start with a SaveJSON call and then get incremental data through the WS interface.

Could you point me at any clients using the WS interface, to use as a template?

**Comment by dhmay** [comment]
(incidentally, if you know of any leagues where multiple people are running jamstats during live games, I'd love to hear about it! Have to fix the scoreboard load issue, of course, but honestly I'd be elated)

**Comment by frank-weinberg** [comment]
I have no reports of slowdown actually occuring in the field. At this time that is just a theoretical possibility. (Thus I also don't consider this bug to be of especially high priority. But it should be addressed at some point and as this change would also allow you to access wsproxy, you might actually prioritize it higher for that added feature.)

Despite using the filename of the internal autosave, you are not receiving that autosave but a file that is filtered for sensitive data like twitter OAuth tokens or session keys. And that file is regenerated for each call as the assumption is that calls are infrequent and users may want changes included they made in the last few seconds.

On WS the first push after you register will contain the full data for the subset you register for, any subsequent push will then contain the delta to the previous push.

See https://github.com/rollerderby/scoreboard/wiki/WebSocket-Commands#low-level-websocket-interface for a description of the interface. Regarding how to set up a WS connection in Python, I'd assume Google should be able to give pointers. The JS "client" used by the CRG frontend is in html/json/WS.json (but presumably of limited help as it's a wrapper instead of a true client in addition to being a different language).

**Comment by dhmay** [comment]
Thanks! I'll muddle through the technical details; I'm sure I can work it out.

I'll aim to make the change to the WS API in the next week or so and put out a new release. I'll post about the release to the scoreboard FB group and encourage anyone using jamstats to upgrade to avoid overtaxing their scoreboards.

**Comment by dhmay** [comment]
Done! [Jamstats 1.0.0](https://github.com/dhmay/jamstats/releases/tag/v1.0.0-beta), just released, uses websockets as you described. I'll reach out to the scoreboard facebook group and ask people to upgrade.
